name: zad10-workflow
on: workflow_dispatch
jobs:
  dockerCI:
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        uses: actions/checkout@v4
      - id: qemu
        uses: docker/setup-qemu-action@v3
      - id: buildx
        uses: docker/setup-buildx-action@v3
      - id: docker_login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
      - id: docker_build
        uses: docker/build-push-action@v5
        with:
          context: ./
          platforms: linux/arm64/v8,linux/amd64
          file: ./Dockerfile
          push: true
          tags: docker.io/redek/zad10:latest
          cache-from: type=registry,ref=docker.io/redek/zad10:latest
          cache-to: type=inline
  kubernetesCI:
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        uses: actions/checkout@v4
        with:
          repository: redeek/zad10-config
          token: ${{ secrets.TOKEN }}
      - run: |
          git config user.name Redeek
          git config user.email mati.red@gmail.com
          sed -i -E "s/[0-9a-f]{40}/${{ github.sha }}/g" zad10-deploy.yml
          git add .
          git commit -m "workflow"
          git push
  
